# Generated by Django 5.1.7 on 2025-03-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('formacao_academica', models.JSONField(blank=True, null=True)),
                ('xp_profissional', models.JSONField(blank=True, null=True)),
                ('interesse', models.JSONField(blank=True, null=True)),
                ('idioma', models.JSONField(blank=True, null=True)),
                ('competencias', models.JSONField(blank=True, null=True)),
                ('atividade', models.JSONField(blank=True, null=True)),
                ('certificado', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário Customizado',
                'verbose_name_plural': 'Usuários Customizados',
            },
        ),
    ]
